title: "Pirikli's Creative Journey"
description: "Exploring creativity, writing, and personal growth as an Azerbaijani poet and storyteller."
author: Pirikli
theme: minima

minima:
  social_links:
    twitter: your_twitter_handle
    github: pirikli

plugins:
  - jekyll-seo-tag
  - jekyll-feed
header_pages:
  - _pages/about.md

version: 1.0.1
